services:
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v24.2.8
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp=1
      - --memory=1G
      - --reserve-memory=0M
      - --node-id=0
      - --check=false
      - --kafka-addr=PLAINTEXT://0.0.0.0:9092,OUTSIDE://0.0.0.0:19092
      - --advertise-kafka-addr=PLAINTEXT://redpanda:9092,OUTSIDE://localhost:19092
    ports:
      - "19092:19092"
      - "9644:9644"
    volumes:
      - redpanda_data:/var/lib/redpanda/data

  clickhouse:
    image: clickhouse/clickhouse-server:24.8
    environment:
      CLICKHOUSE_USER: airflow
      CLICKHOUSE_PASSWORD: airflow
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse

  airflow:
    build:
      context: .
      dockerfile: airflow/Dockerfile
    depends_on:
      - redpanda
      - clickhouse
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "False"
      AIRFLOW__API__AUTH_BACKENDS: airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session
      KAFKA_BROKER: redpanda:9092
      KAFKA_TOPIC: weather_raw
      CLICKHOUSE_HOST: clickhouse
      CLICKHOUSE_PORT: "8123"
      CLICKHOUSE_DATABASE: default
      CLICKHOUSE_USER: airflow
      CLICKHOUSE_PASSWORD: airflow
      DELTA_TABLE_PATH: /opt/airflow/lakehouse/weather_metrics
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./lakehouse:/opt/airflow/lakehouse
      - ./airflow/logs:/opt/airflow/logs
    command: |
      bash -c "set -e;
      airflow db init || true;
      airflow users create --username admin --firstname Admin --lastname User --role Admin --email admin@example.com --password admin || true;
      airflow scheduler & exec airflow webserver"

  metabase:
    image: metabase/metabase:v0.53.11
    depends_on:
      - clickhouse
    ports:
      - "3000:3000"
    volumes:
      - metabase_data:/metabase-data

volumes:
  redpanda_data:
  clickhouse_data:
  metabase_data:
